import { Product, Category, Store } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'iPhone 16 Pro',
    stock: 18,
    category: 'Phones',
    location: '4 stores',
    status: 'Active',
    imageUrl: 'https://www.ais.th/content/dam/ais/consumer/store/devices/apple/iphone/iphone-16-series/iphone-16-pro/iphone-16-pro-desert-titanium.png',
    price: 999.0,
    description: '6.3" Super Retina XDR display with A18 Pro chip and titanium design.',
  },
  {
    id: '2',
    name: 'Samsung Galaxy S25',
    stock: 14,
    category: 'Phones',
    location: '3 stores',
    status: 'Active',
    imageUrl: 'https://titan.com.pa/cdn/shop/files/samsung-galaxy-s25-ultra-256gb-gris-samsung-11053855-4791522.jpg?v=1762609657&width=1445',
    price: 899.0,
    description: 'Flagship Android phone with AI camera and long-lasting battery.',
  },
  {
    id: '3',
    name: 'MacBook Air M3',
    stock: 9,
    category: 'Laptops',
    location: '2 stores',
    status: 'Active',
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=200&h=200&fit=crop',
    price: 1299.0,
    description: '13-inch ultralight laptop powered by Apple M3 for everyday work.',
  },
  {
    id: '4',
    name: 'Sony WH-1000XM5',
    stock: 22,
    category: 'Audio',
    location: '4 stores',
    status: 'Active',
    imageUrl: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=200&h=200&fit=crop',
    price: 349.99,
    description: 'Industry-leading noise cancelling wireless headphones.',
  },
  {
    id: '5',
    name: 'iPad Pro 11"',
    stock: 11,
    category: 'Tablets',
    location: '3 stores',
    status: 'Active',
    imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=200&h=200&fit=crop',
    price: 799.0,
    description: 'Liquid Retina display tablet with M4 chip and Apple Pencil support.',
  },
  {
    id: '6',
    name: 'Apple Watch Ultra 2',
    stock: 16,
    category: 'Wearables',
    location: '3 stores',
    status: 'Active',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNYHOkqiSwLKcyQcSeXGLE_597kvHPrEbyp8V5VyfWdV1ziNz2H5yYBYw&s=10',
    price: 799.0,
    description: 'Rugged smartwatch with precision GPS and multi-day battery life.',
  },
  {
    id: '7',
    name: 'Logitech MX Master 3S',
    stock: 30,
    category: 'Accessories',
    location: '4 stores',
    status: 'Active',
    imageUrl: 'https://www.istudio.store/cdn/shop/files/LOGITECHMXMaster4-Graphite.003.jpg?v=1759220917&width=823',
    price: 99.99,
    description: 'Ergonomic wireless mouse with MagSpeed scrolling for productivity.',
  },
  {
    id: '8',
    name: 'AirPods Pro 2',
    stock: 28,
    category: 'Audio',
    location: '4 stores',
    status: 'Active',
    imageUrl: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=200&h=200&fit=crop',
    price: 249.0,
    description: 'Active noise cancelling earbuds with MagSafe charging case.',
  },
];

export const categories: Category[] = [
  { id: '1', name: 'Phones', count: 24, icon: 'PH' },
  { id: '2', name: 'Laptops', count: 12, icon: 'LT' },
  { id: '3', name: 'Tablets', count: 10, icon: 'TB' },
  { id: '4', name: 'Audio', count: 18, icon: 'AU' },
  { id: '5', name: 'Wearables', count: 14, icon: 'WR' },
  { id: '6', name: 'Accessories', count: 32, icon: 'AC' },
];

export const stores: Store[] = [
  {
    id: '1',
    name: 'Manchester Store',
    city: 'Manchester',
    employees: 12,
    products: 240,
    orders: 86,
    satisfaction: 92,
  },
  {
    id: '2',
    name: 'Yorkshire Store',
    city: 'Yorkshire',
    employees: 8,
    products: 180,
    orders: 54,
    satisfaction: 88,
  },
  {
    id: '3',
    name: 'Hull Store',
    city: 'Hull',
    employees: 6,
    products: 120,
    orders: 41,
    satisfaction: 85,
  },
  {
    id: '4',
    name: 'Leicester Store',
    city: 'Leicester',
    employees: 10,
    products: 200,
    orders: 67,
    satisfaction: 90,
  },
];

export const recentActivity = [
  { id: '1', text: 'New order #1042 from Manchester', time: '2m ago' },
  { id: '2', text: 'Stock updated: iPhone 16 Pro', time: '15m ago' },
  { id: '3', text: 'Category Phones restocked', time: '1h ago' },
  { id: '4', text: 'New product added: AirPods Pro 2', time: '3h ago' },
];

export const topCategories = [
  { name: 'Phones', sales: 420 },
  { name: 'Audio', sales: 280 },
  { name: 'Accessories', sales: 195 },
];
